name: markdown_editor
description: A TextField Widget that allow you to convert easily what's in the
  TextField to Markdown.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.2.0
homepage: https://github.com/Mockerize-io/markdown_editor
repository: https://github.com/Mockerize-io/markdown_editor

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.23
  font_awesome_flutter: ^10.7.0
  markdown: ^7.2.2

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

# To add assets to your package, add an assets section, like this:
# assets:
#   - packages/markdown_editor/assets/loading.gif
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
